Number of literals: 12
Constructing lookup tables:
Post filtering unreachable actions: 
No semaphore facts found, returning
[01;34mNo analytic limits found, not considering limit effects of goal-only operators[00m
- Duration of (harvest-energy vehicle1) is not constant-bounded
Non-constant-bounded duration-dependent effect ((battery-level vehicle1) +=10.000*?duration) makes effects on 0 be order-dependent
[i] Not abstracting out TIL (is-in data10 turbine10)
[i] Not abstracting out TIL (is-turbine-wp waypoint42 turbine10)
Pruning (retrieve-data vehicle1 data10 waypoint42 currenttide turbine10) - temporal contradiction: start min/max = 9223372036854776.000/23111.099; end min/max = 20.000/23131.099; duration min/max = 20.000/20.000
None of the ground temporal actions in this problem have been recognised as compression-safe
; Goals unreachable from the initial state
;; Problem unsolvable!
; Time 0.00
