Number of literals: 15
Constructing lookup tables:
Post filtering unreachable actions: 
No semaphore facts found, returning
[01;34mNo analytic limits found, not considering limit effects of goal-only operators[00m
- Duration of (harvest-energy vehicle2) is not constant-bounded
Non-constant-bounded duration-dependent effect ((battery-level vehicle2) +=10.000*?duration) makes effects on 0 be order-dependent
[i] Not abstracting out TIL (is-in data14 turbine14)
[i] Not abstracting out TIL (is-turbine-wp waypoint58 turbine14)
Pruning (retrieve-data vehicle2 data14 waypoint58 currenttide turbine14) - temporal contradiction: start min/max = 9223372036854776.000/23111.099; end min/max = 20.000/23131.099; duration min/max = 20.000/20.000
None of the ground temporal actions in this problem have been recognised as compression-safe
; Goals unreachable from the initial state
;; Problem unsolvable!
; Time 0.00
