(define (problem task)
(:domain d_tank)
(:objects
    auv0 - vehicle0
    auv1 - vehicle1
    wp_init_auv0 wp_init_auv1 wp_turbine0_point0 wp_turbine0_point1 wp_turbine0_point2 wp_turbine0_point3 wp_turbine0_point4 wp_turbine0_point5 wp_turbine0_point6 wp_turbine0_point7 wp_turbine0_point8 wp_turbine1_point0 wp_turbine1_point1 wp_turbine1_point2 wp_turbine1_point3 wp_turbine1_point4 wp_turbine1_point5 wp_turbine1_point6 wp_turbine1_point7 wp_turbine1_point8 wp_turbine2_point0 wp_turbine2_point1 wp_turbine2_point2 wp_turbine2_point3 wp_turbine2_point4 wp_turbine2_point5 wp_turbine2_point6 wp_turbine2_point7 wp_turbine2_point8 wp_turbine3_point0 wp_turbine3_point1 wp_turbine3_point2 wp_turbine3_point3 wp_turbine3_point4 wp_turbine3_point5 wp_turbine3_point6 wp_turbine3_point7 wp_turbine3_point8 wp_turbine4_point0 wp_turbine4_point1 wp_turbine4_point2 wp_turbine4_point3 wp_turbine4_point4 wp_turbine4_point5 wp_turbine4_point6 wp_turbine4_point7 wp_turbine4_point8 wp_turbine5_point0 wp_turbine5_point1 wp_turbine5_point2 wp_turbine5_point3 wp_turbine5_point4 wp_turbine5_point5 wp_turbine5_point6 wp_turbine5_point7 wp_turbine5_point8 - waypoint
    data0 data1 - data
)
(:init
    (can-move wp_turbine0_point0 wp_turbine0_point1)
    (can-move wp_turbine0_point1 wp_turbine0_point0)
    (can-move wp_turbine0_point1 wp_turbine0_point2)
    (can-move wp_turbine0_point2 wp_turbine0_point0)
    (can-move wp_turbine0_point2 wp_turbine0_point3)
    (can-move wp_turbine0_point3 wp_turbine0_point0)
    (can-move wp_turbine0_point3 wp_turbine0_point4)
    (can-move wp_turbine0_point4 wp_turbine0_point0)
    (can-move wp_turbine0_point4 wp_turbine0_point5)
    (can-move wp_turbine0_point5 wp_turbine0_point0)
    (can-move wp_turbine0_point5 wp_turbine0_point6)
    (can-move wp_turbine0_point6 wp_turbine0_point0)
    (can-move wp_turbine0_point6 wp_turbine0_point7)
    (can-move wp_turbine0_point7 wp_turbine0_point0)
    (can-move wp_turbine0_point7 wp_turbine0_point8)
    (can-move wp_turbine0_point8 wp_turbine0_point0)
    (can-move wp_turbine1_point0 wp_turbine1_point1)
    (can-move wp_turbine1_point1 wp_turbine1_point0)
    (can-move wp_turbine1_point1 wp_turbine1_point2)
    (can-move wp_turbine1_point2 wp_turbine1_point0)
    (can-move wp_turbine1_point2 wp_turbine1_point3)
    (can-move wp_turbine1_point3 wp_turbine1_point0)
    (can-move wp_turbine1_point3 wp_turbine1_point4)
    (can-move wp_turbine1_point4 wp_turbine1_point0)
    (can-move wp_turbine1_point4 wp_turbine1_point5)
    (can-move wp_turbine1_point5 wp_turbine1_point0)
    (can-move wp_turbine1_point5 wp_turbine1_point6)
    (can-move wp_turbine1_point6 wp_turbine1_point0)
    (can-move wp_turbine1_point6 wp_turbine1_point7)
    (can-move wp_turbine1_point7 wp_turbine1_point0)
    (can-move wp_turbine1_point7 wp_turbine1_point8)
    (can-move wp_turbine1_point8 wp_turbine1_point0)
    (can-move wp_turbine2_point0 wp_turbine2_point1)
    (can-move wp_turbine2_point1 wp_turbine2_point0)
    (can-move wp_turbine2_point1 wp_turbine2_point2)
    (can-move wp_turbine2_point2 wp_turbine2_point0)
    (can-move wp_turbine2_point2 wp_turbine2_point3)
    (can-move wp_turbine2_point3 wp_turbine2_point0)
    (can-move wp_turbine2_point3 wp_turbine2_point4)
    (can-move wp_turbine2_point4 wp_turbine2_point0)
    (can-move wp_turbine2_point4 wp_turbine2_point5)
    (can-move wp_turbine2_point5 wp_turbine2_point0)
    (can-move wp_turbine2_point5 wp_turbine2_point6)
    (can-move wp_turbine2_point6 wp_turbine2_point0)
    (can-move wp_turbine2_point6 wp_turbine2_point7)
    (can-move wp_turbine2_point7 wp_turbine2_point0)
    (can-move wp_turbine2_point7 wp_turbine2_point8)
    (can-move wp_turbine2_point8 wp_turbine2_point0)
    (can-move wp_turbine3_point0 wp_turbine3_point1)
    (can-move wp_turbine3_point1 wp_turbine3_point0)
    (can-move wp_turbine3_point1 wp_turbine3_point2)
    (can-move wp_turbine3_point2 wp_turbine3_point0)
    (can-move wp_turbine3_point2 wp_turbine3_point3)
    (can-move wp_turbine3_point3 wp_turbine3_point0)
    (can-move wp_turbine3_point3 wp_turbine3_point4)
    (can-move wp_turbine3_point4 wp_turbine3_point0)
    (can-move wp_turbine3_point4 wp_turbine3_point5)
    (can-move wp_turbine3_point5 wp_turbine3_point0)
    (can-move wp_turbine3_point5 wp_turbine3_point6)
    (can-move wp_turbine3_point6 wp_turbine3_point0)
    (can-move wp_turbine3_point6 wp_turbine3_point7)
    (can-move wp_turbine3_point7 wp_turbine3_point0)
    (can-move wp_turbine3_point7 wp_turbine3_point8)
    (can-move wp_turbine3_point8 wp_turbine3_point0)
    (can-move wp_turbine4_point0 wp_turbine4_point1)
    (can-move wp_turbine4_point1 wp_turbine4_point0)
    (can-move wp_turbine4_point1 wp_turbine4_point2)
    (can-move wp_turbine4_point2 wp_turbine4_point0)
    (can-move wp_turbine4_point2 wp_turbine4_point3)
    (can-move wp_turbine4_point3 wp_turbine4_point0)
    (can-move wp_turbine4_point3 wp_turbine4_point4)
    (can-move wp_turbine4_point4 wp_turbine4_point0)
    (can-move wp_turbine4_point4 wp_turbine4_point5)
    (can-move wp_turbine4_point5 wp_turbine4_point0)
    (can-move wp_turbine4_point5 wp_turbine4_point6)
    (can-move wp_turbine4_point6 wp_turbine4_point0)
    (can-move wp_turbine4_point6 wp_turbine4_point7)
    (can-move wp_turbine4_point7 wp_turbine4_point0)
    (can-move wp_turbine4_point7 wp_turbine4_point8)
    (can-move wp_turbine4_point8 wp_turbine4_point0)
    (can-move wp_turbine5_point0 wp_turbine5_point1)
    (can-move wp_turbine5_point1 wp_turbine5_point0)
    (can-move wp_turbine5_point1 wp_turbine5_point2)
    (can-move wp_turbine5_point2 wp_turbine5_point0)
    (can-move wp_turbine5_point2 wp_turbine5_point3)
    (can-move wp_turbine5_point3 wp_turbine5_point0)
    (can-move wp_turbine5_point3 wp_turbine5_point4)
    (can-move wp_turbine5_point4 wp_turbine5_point0)
    (can-move wp_turbine5_point4 wp_turbine5_point5)
    (can-move wp_turbine5_point5 wp_turbine5_point0)
    (can-move wp_turbine5_point5 wp_turbine5_point6)
    (can-move wp_turbine5_point6 wp_turbine5_point0)
    (can-move wp_turbine5_point6 wp_turbine5_point7)
    (can-move wp_turbine5_point7 wp_turbine5_point0)
    (can-move wp_turbine5_point7 wp_turbine5_point8)
    (can-move wp_turbine5_point8 wp_turbine5_point0)
    (can-move wp_init_auv0 wp_turbine0_point0)
    (can-move wp_init_auv1 wp_turbine0_point0)
    (can-move wp_turbine0_point0 wp_turbine1_point0)
    (can-move wp_turbine0_point0 wp_turbine2_point0)
    (can-move wp_turbine0_point0 wp_turbine3_point0)
    (can-move wp_turbine0_point0 wp_turbine4_point0)
    (can-move wp_turbine0_point0 wp_turbine5_point0)
    (can-move wp_turbine1_point0 wp_turbine0_point0)
    (can-move wp_turbine1_point0 wp_turbine2_point0)
    (can-move wp_turbine1_point0 wp_turbine3_point0)
    (can-move wp_turbine1_point0 wp_turbine4_point0)
    (can-move wp_turbine1_point0 wp_turbine5_point0)
    (can-move wp_turbine2_point0 wp_turbine0_point0)
    (can-move wp_turbine2_point0 wp_turbine1_point0)
    (can-move wp_turbine2_point0 wp_turbine3_point0)
    (can-move wp_turbine2_point0 wp_turbine4_point0)
    (can-move wp_turbine2_point0 wp_turbine5_point0)
    (can-move wp_turbine3_point0 wp_turbine0_point0)
    (can-move wp_turbine3_point0 wp_turbine1_point0)
    (can-move wp_turbine3_point0 wp_turbine2_point0)
    (can-move wp_turbine3_point0 wp_turbine4_point0)
    (can-move wp_turbine3_point0 wp_turbine5_point0)
    (can-move wp_turbine4_point0 wp_turbine0_point0)
    (can-move wp_turbine4_point0 wp_turbine1_point0)
    (can-move wp_turbine4_point0 wp_turbine2_point0)
    (can-move wp_turbine4_point0 wp_turbine3_point0)
    (can-move wp_turbine4_point0 wp_turbine5_point0)
    (can-move wp_turbine5_point0 wp_turbine0_point0)
    (can-move wp_turbine5_point0 wp_turbine1_point0)
    (can-move wp_turbine5_point0 wp_turbine2_point0)
    (can-move wp_turbine5_point0 wp_turbine3_point0)
    (can-move wp_turbine5_point0 wp_turbine4_point0)

    (is-in data0 wp_turbine0_point8)
    (is-in data1 wp_turbine1_point8)


    (at auv0 wp_init_auv0)
    (at auv1 wp_init_auv1)

    (is-at-surface wp_turbine0_point0)
    (is-at-surface wp_turbine1_point0)


    (empty auv0)
    (empty auv1)

    (localized auv0)
    (localized auv1)


)
(:goal (and
    (data-sent data0)
    (data-sent data1)
))
(:metric minimize (total-time))
)
